### ISSUE TITLE
Getting syntax illegal error.  

### ISSUE THREAD

**Issue by JamesJensen3** [chrisred/logicmonitor-zerto#2]
Getting errors for VPG data, resulting in "No Data" for the instances.
It did pull in the VPGs, it is the data for each VPG instance that has no data.

The embed groovy script syntax is illegal - org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script222.groovy: 155: unable to resolve class BasicNameValuePair 
 @ line 155, column 18.
       postData.add(new BasicNameValuePair('grant_type', 'client_credentials'))
                    ^

Script222.groovy: 156: unable to resolve class BasicNameValuePair 
 @ line 156, column 18.
       postData.add(new BasicNameValuePair('client_id', clientId))
                    ^

Script222.groovy: 157: unable to resolve class BasicNameValuePair 
 @ line 157, column 18.
       postData.add(new BasicNameValuePair('client_secret', clientSecret))
                    ^

**Comment by chrisred** [comment]
Hi @TheThird78, thanks for pointing that out. I'll update the files. You can add this line at the top of the Groovy script in the "Collection" section when editing the DataSource, that should fix it.

`import org.apache.http.message.BasicNameValuePair`

**Comment by JamesJensen3** [comment]
Thank you!  that did fix it. 
And thank you for this great LogicModule!
